spring:
  jpa:
    enabled: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:DITEST;DB_CLOSE_ON_EXIT=FALSE;QUERY_CACHE_SIZE=0;
    username: sa
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console